env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
plugins:
  - "@typescript-eslint"
rules: {}
