title = "Rust course"
description = "A Rust course at MIM UW"
base_url = "https://mimuw-jnp2-rust.github.io"
compile_sass = true
build_search_index = true
generate_feeds = true

default_language = "en"

[markdown]

highlight_code = true
highlight_theme = "Tomorrow"